#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2015 OpenWrt.org

START=99

start() {
	echo -e "Starting bot..."
	pgrep -f /etc/tgnodewrt/index.js > /dev/null
    if [ $? -eq 0 ]; then
		# echo -e "Found running process"
		kill $(pgrep -f /etc/tgnodewrt/index.js) >/dev/null 2>&1
	fi
	cd /etc/tgnodewrt && node /etc/tgnodewrt/index.js >/dev/null 2>&1 &
	return 0
}

stop() {
	echo -e "Stoping bot.."
	kill $(pgrep -f /etc/tgnodewrt/index.js) >/dev/null 2>&1
}

restart(){
	stop
	sleep 1
	start
}

boot() {
	sleep 10
	/etc/tgnodewrt/command/sh/onstart.sh >/dev/null
	(start >/dev/null 2>&1) &
	return 0
}
