#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2015 OpenWrt.org

START=99

start() {
	if [ ! -f "/var/run/tgnodewrt.pid" ]; then
		echo "1" > /var/run/tgnodewrt.pid
		cd /root/tgnodewrt && node /root/tgnodewrt/index.js >/dev/null 2>&1 &
		/root/tgnodewrt/command/sh/onstart.sh >/dev/null
	fi
	return 0
}

stop() {
	rm -f /var/run/tgnodewrt.pid
	kill $(pgrep -f /root/tgnodewrt) >/dev/null 2>&1
}

restart(){
	stop
	sleep 1
	start
}

boot() {
	(sleep 5 && start >/dev/null 2>&1) &
	return 0
}
